name: AWS Review Trigger

on:
  issue_comment:
    types: [created]

jobs:
  aws_review:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.comment.body, '/aws_review') }} # 只有当评论包含 /aws_review 时触发

    steps:
      - name: Checkout the PR repository
        uses: actions/checkout@v4

      - name: Extract PR URL and /aws_review arguments
        id: extract
        run: |
          COMMENT_BODY="${{ github.event.comment.body }}"
          PR_URL="${{ github.event.issue.pull_request.html_url || github.event.issue.html_url }}"
          PR_URL="${{ github.event.issue.pull_request.html_url || github.event.issue.html_url }}"
          AWS_REVIEW_ARGS=$(echo "$COMMENT_BODY" | sed -n 's/.*/aws_review //p' | tr -d '\n' | tr -d '\r')

          echo "PR_URL=$PR_URL" >> $GITHUB_ENV
          echo "AWS_REVIEW_ARGS=$AWS_REVIEW_ARGS" >> $GITHUB_ENV


      - name: Clone pr-agent-aws repo
        run: |
          git clone https://github.com/guanzhili/pr-agent-aws.git

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd pr-agent-aws
          pip install -r requirements.txt

      - name: Run Python script
        env:
          PR_AGENT_AWS__AWS_ACCESS_KEY_ID: ${{ secrets.PR_AGENT_AWS__AWS_ACCESS_KEY_ID }}
          PR_AGENT_AWS__AWS_REGION_NAME: ${{ secrets.PR_AGENT_AWS__AWS_REGION_NAME }}
          PR_AGENT_AWS__AWS_SECRET_ACCESS_KEY: ${{ secrets.PR_AGENT_AWS__AWS_SECRET_ACCESS_KEY }}
          PR_AGENT_GITHUB__USER_TOKEN: ${{ secrets.PR_AGENT_GITHUB__USER_TOKEN }}
          PR_AGENT_CONFIG__MODEL: ${{ secrets.PR_AGENT_CONFIG__MODEL }}
        run: |
          cd pr-agent-aws
          echo "PR_URL is $PR_URL"
          echo "GITHUB_ENV is $GITHUB_ENV"
          echo "Running command: python -m pr_agent.cli --pr_url \"$PR_URL\" \"$AWS_REVIEW_ARGS\""
          python -m pr_agent.cli --pr_url "$PR_URL" "$AWS_REVIEW_ARGS"