name: AWS Review Trigger

on:
  issue_comment:
    types: [created]

jobs:
  aws_review:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.comment.body, '/aws_review') }} # 只有当评论包含 /aws_review 时触发

    steps:
      - name: Checkout the PR repository
        uses: actions/checkout@v4

      - name: Extract PR URL and /aws_review arguments
        id: extract
        run: |
          COMMENT_BODY="${{ github.event.comment.body }}"
          PR_URL="${{ github.event.issue.pull_request.html_url || github.event.issue.html_url }}"
          PR_URL="${{ github.event.issue.pull_request.html_url || github.event.issue.html_url }}"
          AWS_REVIEW_ARGS=$(echo "$COMMENT_BODY" | sed -n 's|^/aws_review[[:space:]]*||p' | tr -d '\n' | tr -d '\r')

          echo "PR_URL=$PR_URL" >> $GITHUB_ENV
          echo "AWS_REVIEW_ARGS=$AWS_REVIEW_ARGS" >> $GITHUB_ENV


      - name: Clone pr-agent-aws repo
        run: |
          git clone https://github.com/qodo-ai/pr-agent.git

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd pr-agent
          pip install -r requirements.txt
      
      - name: Remove unwanted characters from pr_reviewer_prompts.toml
        run: |
          sed -i 's/(0-3 issues) of//g' ./pr_agent/settings/pr_reviewer_prompts.toml
          cat ./pr_agent/settings/pr_reviewer_prompts.toml # To verify that the changes are applied

      - name: Run Python script
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_REGION_NAME: ${{ secrets.AWS_REGION_NAME }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB.USER_TOKEN: ${{ secrets.GIT_HUB_USER_TOKEN }}
          config.model: ${{ secrets.CONFIG_MODEL }}
        run: |
          cd pr-agent
          echo "PR_URL is $PR_URL"
          echo "GITHUB_ENV is $GITHUB_ENV"
          echo "Running command: python -m pr_agent.cli --pr_url \"$PR_URL\" \"$AWS_REVIEW_ARGS\""
          python -m pr_agent.cli --pr_url $PR_URL $AWS_REVIEW_ARGS